config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  root 'instances#index'
  resources :instances, only: [:index, :show, :new, :create] do
    member do
      post :start
      post :stop
    end
  end
  resources :presets, only: [:index, :new, :create]


  mount Sidekiq::Web, at: '/sidekiq' 
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :preset
  validates :name, presence: true
  
  # They are added after the first validation on the controller
  # validates :instance_id, presence: true
  # validates :flavor_id, presence: true
  # validates :image_id, presence: true
  # validates :private_ip, presence: true
  # validates :public_ip, presence: true
  # validates :dns_name, presence: true
  # validates :private_dns_name, presence: true
  # validates :availability_zone, presence: true
  def self.new_with_server_and_params(params, server)
    Instance.new(
    name: params["name"],
    company: params["company"],
    description: params["description"],
    preset_id: params["preset_id"],
    instance_id: server.id,
    image_id: server.image_id,
    flavor_id: server.flavor_id,
    private_ip: server.private_ip_address,
    public_ip: server.public_ip_address,
    availability_zone: server.availability_zone,
    dns_name: server.dns_name,
    private_dns_name: server.private_dns_name
    )
  end

end

app/models/preset.rb
class Preset < ActiveRecord::Base
  has_many :instances

  validates :name, presence: true
  validates :flavor_id, presence: true
  validates :image_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :find_instance, only: [:show, :action, :start, :stop]
  before_action :find_server, only: [:show]
  

  def index
    @instances = Instance.all
  end

  def show
  end

  def new
    @instance = Instance.new
    @presets = Preset.all
  end

  def create
    @instance = Instance.new(instance_params)
    if @instance.valid?
      CreateInstanceWorker.perform_async(params[:instance])
      flash[:positive] = "#{params[:instance][:name]} is being processed"
      redirect_to instances_path
    else
      render :new
    end
  end

  def start
      InstanceService.start(@instance.id)
      redirect_to :back
   end
   def stop
      InstanceService.stop(@instance.id)
      redirect_to :back
   end
  

  private
    def instance_params
      params.require(:instance).permit(:name, :preset_id, :company, :description)
    end

    def find_instance
      @instance = Instance.find(params[:id])
    end

    def find_server
      @server = InstanceService.get(@instance.id)
    end
end

app/controllers/presets_controller.rb
class PresetsController < ApplicationController
  def index
    @presets = Preset.all
  end

  def new
    @preset = Preset.new
  end

  def create
    @preset = Preset.new(preset_params)
    if @preset.save
      flash[:positive] = "#{params[:name]} preset was created"
      redirect_to presets_path
    else
      render :new
    end
  end

  private
    def preset_params
      params.require(:preset).permit(:name, :image_id, :flavor_id)
    end
end

app/views/instances/index.html.erb
<div class="ui segment container">
  <div class="ui three column divided grid">
    <div class="row">
      <div class="column">
        <%= link_to("New instance", new_instance_path , class:"ui green button") %>
      </div>
      <div class="column">
        <h1 class="ui center center aligned header">Virtual Machines</h1>
      </div>
      <div class="column">
      </div>
    </div>
  </div>
  <% @instances.each do |instance| %>
    <div class="ui segment  container">
      <h2><%= link_to(instance.name, instance_path(instance.id))%></h2>
    </div>
  <% end %>
</div>

app/views/instances/new.html.erb
<div class="ui segment container">
  <div class="ui three column divided grid">
    <div class="row">
      <div class="column">
        <%= link_to("back", instances_path , class:"ui green button") %>
      </div>
      <div class="column">
        <h1 class="ui center center aligned header">Create new virtual Machine</h1>
      </div>
      <div class="column">
      </div>
    </div>
  </div>
  
    <%= render "layouts/errors", obj: @instance %>
    <%= form_for (@instance), html: { class: "ui form"}  do |f| %>
      <div class="field">
        <%= f.label :name  %>
        <%= f.text_field :name  %>
      </div>
      <div class="field">
        <%= f.label :company  %>
        <%= f.text_field :company  %>
      </div>
      <div class="field">
        <%= f.label :description  %>
        <%= f.text_area :description  %>
      </div>
        <div class="field">
        <%= f.label "Preset"  %>
        <%= collection_select(:instance, :preset_id, Preset.all, :id, :name, class: "ui dropdown") %>
      </div>
      <%= f.submit("Create", class: "ui green button")  %>
    <% end  %>
</div>

app/views/instances/show.html.erb
<div class="ui segment container">
  <div class="ui three column divided grid">
    <div class="row">
      <div class="column">
        <%= link_to("Back", instances_path , class: "ui green button") %>
      </div>
      <div class="column">
        <h1 class="ui center aligned header"><%= @instance.name %></h1><h2 class="ui center aligned header"><%= @instance.company %></h2>
      </div>
      <div class="column">
        <h4>Status: <%= @server.state %>
          <% dis = "" %>
          <% if %(pending stopping shutting-down rebooting).include? @server.state 
            dis = "disabled" 
          end %>
          <% if %w(running  pending).include? @server.state %>
            <%= link_to "Stop instance", stop_instance_path(@instance), method: :post, class: "ui red right button #{dis}" %>
          <% else %>
            <%= link_to "Start instance", start_instance_path(@instance), method: :post, class: "ui green right button #{dis}" %>
          <% end %>
        </div>
      </h4>
    </div>
  </div>

  <table class="ui celled padded table">
    <thead>
      <tr>
        <th>Instance ID</th>
        <th>Image ID</th>
        <th >Flavor ID</th>
        <th>Public ip</th>
        <th>DNS name</th>
        <th>Zone</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <%= @instance.instance_id %>
        </td>
        <td class="single line">
          <%= @instance.image_id %>
        </td>
        <td>
          <%= @instance.flavor_id %>
        </td>
        <td>
          <%= @instance.public_ip %>
        </td>
        <td>
          <%= @instance.dns_name %>
        </td>
        <td>
          <%= @instance.availability_zone %>
        </td>
      </tr>
      
    </tbody>
  </table>
  
  <p><h3>description</h3><%= @instance.description %></p>

</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="ui container negative message">
      <div class="ui header">Errors:</div>
      <ul class="list">
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
         <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="">
    <p>Virtual Machine Manager</p>
</div>

app/views/layouts/_messages.html.erb
<div class="ui container">
  <% flash.each do |message_type, message| %>
    <% if message_type == "alert" %>
      <% message_type = "danger" %>
    <% elsif message_type == "notice"  %>
      <% message_type = "positive" %>
    <% end %>
  <div class="ui <%=message_type %> message">
    <i class="close icon"></i> 
    <div class="header">
      Success!
    </div>
    <p>
      <%= message %>
  </p>
  
  </div>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="ui sticky inverted stackable menu">
  <div class="ui container inverted">
      <div class="header item">
        <%= link_to "VMM", root_path %>
      </div>
    <%= link_to("Virtual Machines", instances_path, class: "item") %>
    <%= link_to("Presets", presets_path, class: "item") %>
    <%= link_to("Sidekiq", sidekiq_web_path, target: "_blank", class: "item") %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtualMachineManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'bootstrap' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navigation" %>

 
<div class="ui container">
  <%= render 'layouts/messages' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

<script>
   $(document).ready(function(){
    $('.message .close')
  .on('click', function() {
    $(this)
      .closest('.message')
      .transition('fade')
    ;
  })
;

}); 
   
</script>
</body>
</html>

app/views/presets/index.html.erb
<div class="ui segment container">
  <div class="ui three column divided grid">
    <div class="row">
      <div class="column">
        <%= link_to("New preset", new_preset_path , class:"ui green button") %>
      </div>
      <div class="column">
        <h1 class="ui center center aligned header">Presets</h1>
      </div>
      <div class="column">
        </div>
      </h4>
    </div>
  <div class="ui attached segment">

  <% @presets.each do |preset| %>
    <div class="ui segment  container">
      <div class="ui three column divided grid">
        <div class="row">
          <div class="column">
            <h2><%= preset.name %></h2> 
          </div>
        <div class="column">
          <p>Image ID - <%= preset.image_id %></p>
          <p>Flavor ID - <%= preset.flavor_id %></p>
        </div>
        <div class="column">
          
        </div>
      </div>
    </div>
  </div>
  <% end %>

</div>

app/views/presets/new.html.erb
<div class="ui segment container">
  <div class="ui three column divided grid">
    <div class="row">
      <div class="column">
        <%= link_to("back", presets_path , class:"ui green button") %>
      </div>
      <div class="column">
        <h1 class="ui center center aligned header">Create new Preset</h1>
      </div>
      <div class="column">
      </div>
    </div>
  </div>
    <%= render "layouts/errors", obj: @preset %>
    <%= form_for (@preset), html: { class: "ui form"}  do |f| %>
      <div class="field">
        <%= f.label :name  %>
        <%= f.text_field :name  %>
        <div class="field">
        <%= f.label :image_id  %>
        <%= f.text_field :image_id  %>
        <%= f.label :flavor_id  %>
        <%= f.text_field :flavor_id  %>
      </div>
      <%= f.submit("Create", class: "ui green button")  %>
    <% end  %>
</div>

app/views/virtual_machines/show.html.erb
<div class="ui segment container">
  <h1 class="ui center aligned header"><%= @vm.instance_name %></h1>

<h2>id: <%= @vm.instance_id %></h2>
<%= @ec2.state %>
<%= @ec2.public_ip_address %>
</div>